name: Build - Lint - Test - Staging

on:
  push:
    branches: [staging]

env:
  SANITY_CLIENT_TOKEN: ${{ secrets.SANITY_CLIENT_TOKEN }}
  SANITY_GRAPHQL_ENDPOINT: ${{ secrets.SANITY_GRAPHQL_ENDPOINT }}
  SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
  SANITY_DATASET_ID: ${{ secrets.SANITY_DATASET_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Build
        run: yarn build

  lintCode:
    name: Run ESLint
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run ESLint
        run: yarn lint:code

  lintStyle:
    name: Run Stylelint
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Stylelint
        run: yarn lint:style

  lintFormat:
    name: Run Prettier
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Prettier
        run: yarn lint:format

  test:
    name: Run Unit tests
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run tests
        run: yarn test

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    env:
      VERCEL_DEPLOYMENT_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

    outputs:
      DEPLOYMENT_URL: ${{ steps.step1.outputs.DEPLOYMENT_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy & Save URL
        run: echo "DEPLOYMENT_URL=$(vercel -t $VERCEL_DEPLOYMENT_TOKEN -S thesoreon)" >> $GITHUB_ENV

      - name: Alias URL to staging URL
        run: vercel alias set $DEPLOYMENT_URL staging.frontendista.cz -t $VERCEL_DEPLOYMENT_TOKEN

      - name: Save URL to outputs
        id: step1
        run: echo "::set-output name=DEPLOYMENT_URL::$DEPLOYMENT_URL"

  e2e:
    name: Run E2E tests
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: pageLoadTimeout=10000,baseUrl=${{ needs.deploy.outputs.DEPLOYMENT_URL }}
