name: Build - Lint - Test - Production

on:
  release:
    types: created

env:
  SANITY_CLIENT_TOKEN: ${{ secrets.SANITY_CLIENT_TOKEN }}
  SANITY_GRAPHQL_ENDPOINT: ${{ secrets.SANITY_GRAPHQL_ENDPOINT }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Build
        run: yarn build

  lintCode:
    name: Run ESLint
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run ESLint
        run: yarn lint:code

  lintStyle:
    name: Run Stylelint
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Stylelint
        run: yarn lint:style

  lintFormat:
    name: Run Prettier
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Prettier
        run: yarn lint:format

  test:
    name: Run Unit tests
    needs: [lintCode, lintStyle, lintFormat]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run tests
        run: yarn test

  e2e:
    name: Run E2E tests
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn next start -p 3000
          config: pageLoadTimeout=10000,baseUrl=http://localhost:3000

  deploy:
    name: Deploy
    needs: [e2e]
    runs-on: ubuntu-latest

    env:
      VERCEL_DEPLOYMENT_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: vercel --prod -t $VERCEL_DEPLOYMENT_TOKEN -S thesoreon
