name: Build - Lint - Test

on:
  pull_request:
    branches: [main]

env:
  SANITY_CLIENT_TOKEN: ${{ secrets.SANITY_CLIENT_TOKEN }}
  SANITY_GRAPHQL_ENDPOINT: ${{ secrets.SANITY_GRAPHQL_ENDPOINT }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Build
        run: yarn build

  lintCode:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run ESLint
        run: yarn lint:code

  lintStyle:
    name: Run Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Stylelint
        run: yarn lint:style

  lintFormat:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Prettier
        run: yarn lint:format

  test:
    name: Run Unit tests
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run tests
        run: yarn test

  e2e:
    name: Run E2E tests
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn next start -p 3000
          config: pageLoadTimeout=10000,baseUrl=http://localhost:3000

  bundlediff:
    name: Diff Checker
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Report
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: "./.next/static/{chunks,css}/**/*.{js,css}"
          strip-hash: "\\b-[a-z0-9]{1,}\\b"
